<template>
  <div>
    <h1>Allgemeine Gesch&auml;ftsbedingungen</h1>
    <p><strong>1. Geltungsbereich und Vertragssprache</strong></p>
    <p>Lieferungen und Leistungen des Online-Shops www.hochzeitstrauringe.de - Joachim Winkler (nachfolgend hochzeitstrauringe.de) erfolgen auf Basis dieser Allgemeinen Gesch&auml;ftsbedingungen. M&uuml;ndliche Nebenabreden bestehen nicht. Die Vertragssprache ist deutsch. Wir speichern den Vertragstext und senden Ihnen die Bestelldaten und unsere AGB per E-Mail zu. Die AGB k&ouml;nnen Sie jederzeit &uuml;ber den Link oben auf dieser Seite oder in der Navigationsleiste auf der linken Seite einsehen. Ihre Bestelldaten sind aus Sicherheitsgr&uuml;nden nicht mehr &uuml;ber das Internet zug&auml;nglich.</p><p><strong>2. Vertragsabschluss und R&uuml;cktritt</strong></p><p>Die Darstellung des Sortiments von hochzeitstrauringe.de auf dem Online-Shop hochzeitstrauringe.de stellt kein rechtlich bindendes Angebot, sondern einen unverbindlichen Online-Katalog dar. Durch Anklicken des Buttons "Jetzt bestellen" geben Sie eine verbindliche Bestellung der im Warenkorb enthaltenen Waren ab. Die Best&auml;tigung des Eingangs der Bestellung folgt unmittelbar nach dem Absenden der Bestellung. Der Kaufvertrag kommt mit unserer separaten Auftragsbest&auml;tigung oder Lieferung der Waren zustande. Kann Hochzeitstrauringe.de das Angebot des Kunden nicht annehmen, wird der Kunde anstelle der Annahme der Bestellung &uuml;ber die Nichtverf&uuml;gbarkeit informiert. Bereits erbrachte Gegenleistungen des Kunden werden unverz&uuml;glich erstattet.</p><p><strong>3. F&auml;lligkeit und Zahlung</strong></p><p>Der Kaufpreis wird mit Vertragsabschluss f&auml;llig. Die Zahlung kann per Bank&uuml;berweisung, per Kreditkarte oder per PayPal erfolgen.</p><p><strong>4. Verpackung und Versand.</strong> Die Lieferung erfolgt innerhalb Deutschlands versichert und versandkostenfrei.</p><p><strong>5. Lieferung und Lieferfrist</strong></p><p>Die Lieferung von Lagerware erfolgt durch DHL, Hermes, GLS ab Lager an die vom Besteller angegebene Lieferadresse. Die Lieferfristen werden auf der Produktseite in unserem Online-Shop angegeben.</p>
    <p><strong>6. Widerrufsrecht</strong></p><p>Widerrufsrecht f&uuml;r Verbraucher</p><p>(Verbraucher ist jede nat&uuml;rliche Person, die ein Rechtsgesch&auml;ft zu Zwecken abschlie&szlig;t, die &uuml;berwiegend weder ihrer gewerblichen noch ihrer selbstst&auml;ndigen beruflichen T&auml;tigkeit zugerechnet werden kann.)</p><p><span>Widerrufsbelehrung</span></p><p><span>Widerrufsrecht</span></p><p>Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gr&uuml;nden diesen Vertrag zu widerrufen.&nbsp;Die Widerrufsfrist betr&auml;gt vierzehn Tage ab dem Tag,&nbsp;an dem Sie oder ein von Ihnen benannter Dritter,der nicht der Bef&ouml;rderer ist, die Waren in Besitz genommen haben bzw. hat, sofern Sie eine oder mehrere Waren im Rahmen einer einheitlichen Bestellung bestellt haben und diese einheitlich geliefert wird bzw. werden,an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Bef&ouml;rderer ist, die letzte Ware in Besitz genommen haben bzw. hat, sofern Sie mehrere Waren im Rahmen einer einheitlichen Bestellung bestellt haben und diese getrennt geliefert werden;&nbsp;Der Widerruf ist zu richten an:</p>
    <p>Hochzeitstrauringe.de</p>
    <p>Joachim Winkler,&nbsp;Kurze Birken 7,&nbsp;14532 Stahnsdorf</p>
    <p>Tel. 03329/4 39 86 32 E-Mail: info@hochzeitstrauringe.de</p>
    <p><span>Folgen des Widerrufs</span></p><p>Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschlie&szlig;lich der Lieferkosten (mit Ausnahme der zus&auml;tzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, g&uuml;nstigste Standardlieferung gew&auml;hlt haben), unverz&uuml;glich und sp&auml;testens binnen&nbsp;vierzehn Tagen&nbsp;ab dem Tag zur&uuml;ckzuzahlen, an dem die Mitteilung &uuml;ber Ihren Widerruf dieses Vertrags bei uns eingegangen ist. F&uuml;r diese R&uuml;ckzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der urspr&uuml;nglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdr&uuml;cklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser R&uuml;ckzahlung Entgelte berechnet.</p><p>Wir k&ouml;nnen die R&uuml;ckzahlung verweigern, bis wir die Waren wieder zur&uuml;ckerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren zur&uuml;ckgesandt haben, je nachdem, welches der fr&uuml;here Zeitpunkt ist.</p><p>Sie haben die Waren unverz&uuml;glich und in jedem Fall sp&auml;testens binnen&nbsp;vierzehn Tagen&nbsp;ab dem Tag, an dem Sie uns &uuml;ber den Widerruf dieses Vertrags unterrichten, an uns&nbsp;zur&uuml;ckzusenden oder zu &uuml;bergeben. Die Frist ist gewahrt, wenn Sie die Waren vor Ablauf der Frist von&nbsp;vierzehn Tagen&nbsp;absenden.</p><p>Sie tragen die unmittelbaren Kosten der R&uuml;cksendung der Waren.</p><p>ie m&uuml;ssen f&uuml;r einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Pr&uuml;fung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zur&uuml;ckzuf&uuml;hren ist.</p>
    <p>&nbsp;</p>
    <p><strong>Ausschluss- bzw. Erl&ouml;schensgr&uuml;nde</strong></p><p><span>Das Widerrufsrecht besteht<strong> nicht</strong> bei Vertr&auml;gen</span></p><p>zur Lieferung von Waren, die nicht vorgefertigt sind und f&uuml;r deren Herstellung eine individuelle Auswahl oder Bestimmung durch den Verbraucher ma&szlig;geblich ist oder die eindeutig auf die pers&ouml;nlichen Bed&uuml;rfnisse des Verbrauchers zugeschnitten sind.</p>
    <p>Bei den Ringen (mit Ausnahme von Schmuck), handelt es sich ausschlie&szlig;lich um individuelle Einzelanfertigungen. Bei der Lieferung von solchen Waren, die nach Spezifikation des Vertragspartners angefertigt wurden, (Individual- oder Ma&szlig;anfertigungen) besteht kein Widerrufsrecht. Ma&szlig;anfertigungen in diesem Sinne sind alle Produkte, die nach Kundenspezifikation angefertigt werden oder eindeutig auf die pers&ouml;nlichen Bed&uuml;rfnisse zugeschnitten sind (z.B.: Gr&ouml;&szlig;e, Anfertigungen mit Namen und Datum) oder die auf Grund ihrer Beschaffenheit nicht f&uuml;r eine R&uuml;cksendung geeignet sind.</p><p>Dieses ist ausgeschlossen, weil jeder Trauring nach Ihren W&uuml;nschen, speziell f&uuml;r Sie, gefertigt wird. Unser Konzept einer individuellen Anfertigung unter Zuhilfenahme verschiedener Ringmuster und Trauringkonfiguratoren l&auml;sst nur eine kundenspezifische Herstellung zu. Wir unterhalten daher auch kein Lager an Eheringen, welches zum Versand bereit steht.&nbsp; W&uuml;rden wir Trauringe &uuml;ber das Widerrufsrecht zur&uuml;ck nehmen, w&auml;re der Wiederverkauf der zur&uuml;ckgenommenen Ware aufgrund des Konzepts der individuellen Anfertigung nach nicht m&ouml;glich. Die Ware m&uuml;sste zur Wiederverwertbarkeit eingeschmolzen werden. Das Einschmelzen ist allerdings mit hohem Wertverlust verbunden und w&uuml;rde daher einen unverh&auml;ltnism&auml;&szlig;ig hohen Aufwand darstellen.</p>
    <p>Sie k&ouml;nnen das Muster-&nbsp;<a href="https://www.hochzeitstrauringe.de/media//Widerrufsformular_Hochzeitstrauringe.jpg">Widerrufsformular</a>&nbsp;&nbsp;elektronisch ausf&uuml;llen und &uuml;bermitteln.</p>
    <p>&nbsp;</p>
    <p><strong>7. Eigentumsvorbehalt</strong></p><p>Die gelieferte Ware bleibt bis zur vollst&auml;ndigen Bezahlung das Eigentum von hochzeitstrauringe.de.</p><p><strong>8. Abtretungsverbot</strong></p><p>Die Abtretung von Anspr&uuml;chen gegen die Firma hochzeitstrauringe.de. aus dem Vertragsverh&auml;ltnis ist ausgeschlossen.</p><p><strong>9. Erf&uuml;llungsort und Gerichtsstand</strong></p><p>Es gilt deutsches Recht. Im Gesch&auml;ftsverkehr mit Kaufleuten und mit juristischen Personen des &ouml;ffentlichen Rechts, wird als Gerichtsstand f&uuml;r alle Rechtsstreitigkeiten Berlin vereinbart.</p><p><strong>10. Salvatorische Klausel</strong></p><p>Sollte eine Bestimmung ganz oder teilweise unwirksam sein oder ihre Rechtswirksamkeit sp&auml;ter verlieren, wird hierdurch die Wirksamkeit der &uuml;brigen Bestimmungen nicht ber&uuml;hrt. Anstelle der unwirksamen Bestimmungen gelten die gesetzlichen Regelungen.</p>
    <p>Hochzeitstrauringe.de- Kurze Birken 7 - 14532 Stahnsdorf</p>
    <p>Telefon: 03329 4 39 86 32&nbsp; - info@hochzeitstrauringe.de</p>
  </div>
</template>
