<template>
  <div>
    <p><strong>Widerrufsrecht</strong><br><br>Widerrufsrecht f&uuml;r Verbraucher<br>(Verbraucher ist jede nat&uuml;rliche Person, die ein Rechtsgesch&auml;ft zu Zwecken abschlie&szlig;t, die &uuml;berwiegend weder ihrer gewerblichen noch ihrer selbstst&auml;ndigen beruflichen T&auml;tigkeit zugerechnet werden kann.)<br><br><strong>Widerrufsbelehrung</strong><br><br><strong>Widerrufsrecht</strong><br>Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gr&uuml;nden diesen Vertrag zu widerrufen.&nbsp;Die Widerrufsfrist betr&auml;gt vierzehn Tage ab dem Tag,&nbsp;an dem Sie oder ein von Ihnen benannter Dritter,der nicht der Bef&ouml;rderer ist, die Waren in Besitz genommen haben bzw. hat, sofern Sie eine oder mehrere Waren im Rahmen einer einheitlichen Bestellung bestellt haben und diese einheitlich geliefert wird bzw. werden,an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Bef&ouml;rderer ist, die letzte Ware in Besitz genommen haben bzw. hat, sofern Sie mehrere Waren im Rahmen einer einheitlichen Bestellung bestellt haben und diese getrennt geliefert werden;&nbsp;Der Widerruf ist zu richten an:</p>
    <p>Hochzeitstrauringe.de</p>
    <p>Joachim Winkler,&nbsp;Kurze Birken 7,&nbsp;14532 Stahnsdorf</p>
    <p>Tel. 03329/4 39 86 32</p>
    <p>E-Mail: info@hochzeitstrauringe.de<br><br><strong>Folgen des Widerrufs</strong><br><br>Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschlie&szlig;lich der Lieferkosten (mit Ausnahme der zus&auml;tzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, g&uuml;nstigste Standardlieferung gew&auml;hlt haben), unverz&uuml;glich und sp&auml;testens binnen&nbsp;vierzehn Tagen&nbsp;ab dem Tag zur&uuml;ckzuzahlen, an dem die Mitteilung &uuml;ber Ihren Widerruf dieses Vertrags bei uns eingegangen ist. F&uuml;r diese R&uuml;ckzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der urspr&uuml;nglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdr&uuml;cklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser R&uuml;ckzahlung Entgelte berechnet.<br><br>Wir k&ouml;nnen die R&uuml;ckzahlung verweigern, bis wir die Waren wieder zur&uuml;ckerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren zur&uuml;ckgesandt haben, je nachdem, welches der fr&uuml;here Zeitpunkt ist.<br><br>Sie haben die Waren unverz&uuml;glich und in jedem Fall sp&auml;testens binnen&nbsp;vierzehn Tagen&nbsp;ab dem Tag, an dem Sie uns &uuml;ber den Widerruf dieses Vertrags unterrichten, an uns&nbsp;zur&uuml;ckzusenden oder zu &uuml;bergeben. Die Frist ist gewahrt, wenn Sie die Waren vor Ablauf der Frist von&nbsp;vierzehn Tagen&nbsp;absenden.<br><br>Sie tragen die unmittelbaren Kosten der R&uuml;cksendung der Waren.<br><br>Sie m&uuml;ssen f&uuml;r einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Pr&uuml;fung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zur&uuml;ckzuf&uuml;hren ist.</p>
    <p>&nbsp;</p>
    <p><strong>Ausschluss- bzw. Erl&ouml;schensgr&uuml;nde</strong><br><br><strong>Das Widerrufsrecht besteht nicht bei Vertr&auml;gen</strong><br><br>zur Lieferung von Waren, die nicht vorgefertigt sind und f&uuml;r deren Herstellung eine individuelle Auswahl oder Bestimmung durch den Verbraucher ma&szlig;geblich ist oder die eindeutig auf die pers&ouml;nlichen Bed&uuml;rfnisse des Verbrauchers zugeschnitten sind.</p>
    <p>Sie k&ouml;nnen das Muster-&nbsp;<a href="https://www.hochzeitstrauringe.de/media//Widerrufsformular_Hochzeitstrauringe.jpg">Widerrufsformular</a>&nbsp;&nbsp;elektronisch ausf&uuml;llen und &uuml;bermitteln.</p>
    <p><br><br><br><br></p>
  </div>
</template>
